spring:
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.community.dialect.SQLiteDialect
  datasource:
    url: jdbc:sqlite:board.db
    driver-class-name: org.sqlite.JDBC
    username: root
    password: root